// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor_extrinsic.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sensor_5fextrinsic_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sensor_5fextrinsic_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sensor_5fextrinsic_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sensor_5fextrinsic_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sensor_5fextrinsic_2eproto;
namespace tutorial {
class Rotation;
class RotationDefaultTypeInternal;
extern RotationDefaultTypeInternal _Rotation_default_instance_;
class SensorExtrinsic;
class SensorExtrinsicDefaultTypeInternal;
extern SensorExtrinsicDefaultTypeInternal _SensorExtrinsic_default_instance_;
class Translation;
class TranslationDefaultTypeInternal;
extern TranslationDefaultTypeInternal _Translation_default_instance_;
}  // namespace tutorial
PROTOBUF_NAMESPACE_OPEN
template<> ::tutorial::Rotation* Arena::CreateMaybeMessage<::tutorial::Rotation>(Arena*);
template<> ::tutorial::SensorExtrinsic* Arena::CreateMaybeMessage<::tutorial::SensorExtrinsic>(Arena*);
template<> ::tutorial::Translation* Arena::CreateMaybeMessage<::tutorial::Translation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tutorial {

// ===================================================================

class Translation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tutorial.Translation) */ {
 public:
  inline Translation() : Translation(nullptr) {}
  virtual ~Translation();

  Translation(const Translation& from);
  Translation(Translation&& from) noexcept
    : Translation() {
    *this = ::std::move(from);
  }

  inline Translation& operator=(const Translation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Translation& operator=(Translation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Translation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Translation* internal_default_instance() {
    return reinterpret_cast<const Translation*>(
               &_Translation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Translation& a, Translation& b) {
    a.Swap(&b);
  }
  inline void Swap(Translation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Translation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Translation* New() const final {
    return CreateMaybeMessage<Translation>(nullptr);
  }

  Translation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Translation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Translation& from);
  void MergeFrom(const Translation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Translation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tutorial.Translation";
  }
  protected:
  explicit Translation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensor_5fextrinsic_2eproto);
    return ::descriptor_table_sensor_5fextrinsic_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // required double x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // required double y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // required double z = 3;
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:tutorial.Translation)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double x_;
  double y_;
  double z_;
  friend struct ::TableStruct_sensor_5fextrinsic_2eproto;
};
// -------------------------------------------------------------------

class Rotation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tutorial.Rotation) */ {
 public:
  inline Rotation() : Rotation(nullptr) {}
  virtual ~Rotation();

  Rotation(const Rotation& from);
  Rotation(Rotation&& from) noexcept
    : Rotation() {
    *this = ::std::move(from);
  }

  inline Rotation& operator=(const Rotation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rotation& operator=(Rotation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Rotation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rotation* internal_default_instance() {
    return reinterpret_cast<const Rotation*>(
               &_Rotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Rotation& a, Rotation& b) {
    a.Swap(&b);
  }
  inline void Swap(Rotation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rotation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Rotation* New() const final {
    return CreateMaybeMessage<Rotation>(nullptr);
  }

  Rotation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Rotation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Rotation& from);
  void MergeFrom(const Rotation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rotation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tutorial.Rotation";
  }
  protected:
  explicit Rotation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensor_5fextrinsic_2eproto);
    return ::descriptor_table_sensor_5fextrinsic_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // required double x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // required double y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // required double z = 3;
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // required double w = 4;
  bool has_w() const;
  private:
  bool _internal_has_w() const;
  public:
  void clear_w();
  double w() const;
  void set_w(double value);
  private:
  double _internal_w() const;
  void _internal_set_w(double value);
  public:

  // @@protoc_insertion_point(class_scope:tutorial.Rotation)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double x_;
  double y_;
  double z_;
  double w_;
  friend struct ::TableStruct_sensor_5fextrinsic_2eproto;
};
// -------------------------------------------------------------------

class SensorExtrinsic PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tutorial.SensorExtrinsic) */ {
 public:
  inline SensorExtrinsic() : SensorExtrinsic(nullptr) {}
  virtual ~SensorExtrinsic();

  SensorExtrinsic(const SensorExtrinsic& from);
  SensorExtrinsic(SensorExtrinsic&& from) noexcept
    : SensorExtrinsic() {
    *this = ::std::move(from);
  }

  inline SensorExtrinsic& operator=(const SensorExtrinsic& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorExtrinsic& operator=(SensorExtrinsic&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SensorExtrinsic& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SensorExtrinsic* internal_default_instance() {
    return reinterpret_cast<const SensorExtrinsic*>(
               &_SensorExtrinsic_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SensorExtrinsic& a, SensorExtrinsic& b) {
    a.Swap(&b);
  }
  inline void Swap(SensorExtrinsic* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorExtrinsic* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SensorExtrinsic* New() const final {
    return CreateMaybeMessage<SensorExtrinsic>(nullptr);
  }

  SensorExtrinsic* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SensorExtrinsic>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SensorExtrinsic& from);
  void MergeFrom(const SensorExtrinsic& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorExtrinsic* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tutorial.SensorExtrinsic";
  }
  protected:
  explicit SensorExtrinsic(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensor_5fextrinsic_2eproto);
    return ::descriptor_table_sensor_5fextrinsic_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // repeated .tutorial.Translation translation = 1;
  int translation_size() const;
  private:
  int _internal_translation_size() const;
  public:
  void clear_translation();
  ::tutorial::Translation* mutable_translation(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Translation >*
      mutable_translation();
  private:
  const ::tutorial::Translation& _internal_translation(int index) const;
  ::tutorial::Translation* _internal_add_translation();
  public:
  const ::tutorial::Translation& translation(int index) const;
  ::tutorial::Translation* add_translation();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Translation >&
      translation() const;

  // repeated .tutorial.Rotation rotation = 2;
  int rotation_size() const;
  private:
  int _internal_rotation_size() const;
  public:
  void clear_rotation();
  ::tutorial::Rotation* mutable_rotation(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Rotation >*
      mutable_rotation();
  private:
  const ::tutorial::Rotation& _internal_rotation(int index) const;
  ::tutorial::Rotation* _internal_add_rotation();
  public:
  const ::tutorial::Rotation& rotation(int index) const;
  ::tutorial::Rotation* add_rotation();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Rotation >&
      rotation() const;

  // @@protoc_insertion_point(class_scope:tutorial.SensorExtrinsic)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Translation > translation_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Rotation > rotation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensor_5fextrinsic_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Translation

// required double x = 1;
inline bool Translation::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Translation::has_x() const {
  return _internal_has_x();
}
inline void Translation::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Translation::_internal_x() const {
  return x_;
}
inline double Translation::x() const {
  // @@protoc_insertion_point(field_get:tutorial.Translation.x)
  return _internal_x();
}
inline void Translation::_internal_set_x(double value) {
  _has_bits_[0] |= 0x00000001u;
  x_ = value;
}
inline void Translation::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:tutorial.Translation.x)
}

// required double y = 2;
inline bool Translation::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Translation::has_y() const {
  return _internal_has_y();
}
inline void Translation::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Translation::_internal_y() const {
  return y_;
}
inline double Translation::y() const {
  // @@protoc_insertion_point(field_get:tutorial.Translation.y)
  return _internal_y();
}
inline void Translation::_internal_set_y(double value) {
  _has_bits_[0] |= 0x00000002u;
  y_ = value;
}
inline void Translation::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:tutorial.Translation.y)
}

// required double z = 3;
inline bool Translation::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Translation::has_z() const {
  return _internal_has_z();
}
inline void Translation::clear_z() {
  z_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Translation::_internal_z() const {
  return z_;
}
inline double Translation::z() const {
  // @@protoc_insertion_point(field_get:tutorial.Translation.z)
  return _internal_z();
}
inline void Translation::_internal_set_z(double value) {
  _has_bits_[0] |= 0x00000004u;
  z_ = value;
}
inline void Translation::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:tutorial.Translation.z)
}

// -------------------------------------------------------------------

// Rotation

// required double x = 1;
inline bool Rotation::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Rotation::has_x() const {
  return _internal_has_x();
}
inline void Rotation::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Rotation::_internal_x() const {
  return x_;
}
inline double Rotation::x() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.x)
  return _internal_x();
}
inline void Rotation::_internal_set_x(double value) {
  _has_bits_[0] |= 0x00000001u;
  x_ = value;
}
inline void Rotation::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:tutorial.Rotation.x)
}

// required double y = 2;
inline bool Rotation::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Rotation::has_y() const {
  return _internal_has_y();
}
inline void Rotation::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Rotation::_internal_y() const {
  return y_;
}
inline double Rotation::y() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.y)
  return _internal_y();
}
inline void Rotation::_internal_set_y(double value) {
  _has_bits_[0] |= 0x00000002u;
  y_ = value;
}
inline void Rotation::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:tutorial.Rotation.y)
}

// required double z = 3;
inline bool Rotation::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Rotation::has_z() const {
  return _internal_has_z();
}
inline void Rotation::clear_z() {
  z_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Rotation::_internal_z() const {
  return z_;
}
inline double Rotation::z() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.z)
  return _internal_z();
}
inline void Rotation::_internal_set_z(double value) {
  _has_bits_[0] |= 0x00000004u;
  z_ = value;
}
inline void Rotation::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:tutorial.Rotation.z)
}

// required double w = 4;
inline bool Rotation::_internal_has_w() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Rotation::has_w() const {
  return _internal_has_w();
}
inline void Rotation::clear_w() {
  w_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double Rotation::_internal_w() const {
  return w_;
}
inline double Rotation::w() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.w)
  return _internal_w();
}
inline void Rotation::_internal_set_w(double value) {
  _has_bits_[0] |= 0x00000008u;
  w_ = value;
}
inline void Rotation::set_w(double value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:tutorial.Rotation.w)
}

// -------------------------------------------------------------------

// SensorExtrinsic

// repeated .tutorial.Translation translation = 1;
inline int SensorExtrinsic::_internal_translation_size() const {
  return translation_.size();
}
inline int SensorExtrinsic::translation_size() const {
  return _internal_translation_size();
}
inline void SensorExtrinsic::clear_translation() {
  translation_.Clear();
}
inline ::tutorial::Translation* SensorExtrinsic::mutable_translation(int index) {
  // @@protoc_insertion_point(field_mutable:tutorial.SensorExtrinsic.translation)
  return translation_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Translation >*
SensorExtrinsic::mutable_translation() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.SensorExtrinsic.translation)
  return &translation_;
}
inline const ::tutorial::Translation& SensorExtrinsic::_internal_translation(int index) const {
  return translation_.Get(index);
}
inline const ::tutorial::Translation& SensorExtrinsic::translation(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.SensorExtrinsic.translation)
  return _internal_translation(index);
}
inline ::tutorial::Translation* SensorExtrinsic::_internal_add_translation() {
  return translation_.Add();
}
inline ::tutorial::Translation* SensorExtrinsic::add_translation() {
  // @@protoc_insertion_point(field_add:tutorial.SensorExtrinsic.translation)
  return _internal_add_translation();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Translation >&
SensorExtrinsic::translation() const {
  // @@protoc_insertion_point(field_list:tutorial.SensorExtrinsic.translation)
  return translation_;
}

// repeated .tutorial.Rotation rotation = 2;
inline int SensorExtrinsic::_internal_rotation_size() const {
  return rotation_.size();
}
inline int SensorExtrinsic::rotation_size() const {
  return _internal_rotation_size();
}
inline void SensorExtrinsic::clear_rotation() {
  rotation_.Clear();
}
inline ::tutorial::Rotation* SensorExtrinsic::mutable_rotation(int index) {
  // @@protoc_insertion_point(field_mutable:tutorial.SensorExtrinsic.rotation)
  return rotation_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Rotation >*
SensorExtrinsic::mutable_rotation() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.SensorExtrinsic.rotation)
  return &rotation_;
}
inline const ::tutorial::Rotation& SensorExtrinsic::_internal_rotation(int index) const {
  return rotation_.Get(index);
}
inline const ::tutorial::Rotation& SensorExtrinsic::rotation(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.SensorExtrinsic.rotation)
  return _internal_rotation(index);
}
inline ::tutorial::Rotation* SensorExtrinsic::_internal_add_rotation() {
  return rotation_.Add();
}
inline ::tutorial::Rotation* SensorExtrinsic::add_rotation() {
  // @@protoc_insertion_point(field_add:tutorial.SensorExtrinsic.rotation)
  return _internal_add_rotation();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Rotation >&
SensorExtrinsic::rotation() const {
  // @@protoc_insertion_point(field_list:tutorial.SensorExtrinsic.rotation)
  return rotation_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sensor_5fextrinsic_2eproto
