// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor_extrinsic.proto

#ifndef PROTOBUF_INCLUDED_sensor_5fextrinsic_2eproto
#define PROTOBUF_INCLUDED_sensor_5fextrinsic_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/extension_set.h> // IWYU pragma: export
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/message.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_sensor_5fextrinsic_2eproto

namespace protobuf_sensor_5fextrinsic_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_sensor_5fextrinsic_2eproto
namespace tutorial {
class Rotation;
class RotationDefaultTypeInternal;
extern RotationDefaultTypeInternal _Rotation_default_instance_;
class SensorExtrinsic;
class SensorExtrinsicDefaultTypeInternal;
extern SensorExtrinsicDefaultTypeInternal _SensorExtrinsic_default_instance_;
class Translation;
class TranslationDefaultTypeInternal;
extern TranslationDefaultTypeInternal _Translation_default_instance_;
} // namespace tutorial
namespace google {
namespace protobuf {
template<>
::tutorial::Rotation *Arena::CreateMaybeMessage<::tutorial::Rotation>(Arena *);
template<>
::tutorial::SensorExtrinsic *Arena::CreateMaybeMessage<::tutorial::SensorExtrinsic>(Arena *);
template<>
::tutorial::Translation *Arena::CreateMaybeMessage<::tutorial::Translation>(Arena *);
} // namespace protobuf
} // namespace google
namespace tutorial {

// ===================================================================

class Translation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tutorial.Translation) */ {
 public:
  Translation();
  virtual ~Translation();

  Translation(const Translation &from);

  inline Translation &operator=(const Translation &from) {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  Translation(Translation &&from) noexcept
      : Translation() {
    *this = ::std::move(from);
  }

  inline Translation &operator=(Translation &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  inline const ::google::protobuf::UnknownFieldSet &unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet *mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor *descriptor();
  static const Translation &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const Translation *internal_default_instance() {
    return reinterpret_cast<const Translation *>(
        &_Translation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
      0;

  void Swap(Translation *other);
  friend void swap(Translation &a, Translation &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Translation *New() const final {
    return CreateMaybeMessage<Translation>(NULL);
  }

  Translation *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<Translation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const Translation &from);
  void MergeFrom(const Translation &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

 private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Translation *other);

 private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }
  inline void *MaybeArenaPtr() const {
    return NULL;
  }

 public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // required double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // required double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:tutorial.Translation)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double x_;
  double y_;
  double z_;
  friend struct ::protobuf_sensor_5fextrinsic_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rotation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tutorial.Rotation) */ {
 public:
  Rotation();
  virtual ~Rotation();

  Rotation(const Rotation &from);

  inline Rotation &operator=(const Rotation &from) {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  Rotation(Rotation &&from) noexcept
      : Rotation() {
    *this = ::std::move(from);
  }

  inline Rotation &operator=(Rotation &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  inline const ::google::protobuf::UnknownFieldSet &unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet *mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor *descriptor();
  static const Rotation &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const Rotation *internal_default_instance() {
    return reinterpret_cast<const Rotation *>(
        &_Rotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
      1;

  void Swap(Rotation *other);
  friend void swap(Rotation &a, Rotation &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rotation *New() const final {
    return CreateMaybeMessage<Rotation>(NULL);
  }

  Rotation *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<Rotation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const Rotation &from);
  void MergeFrom(const Rotation &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

 private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rotation *other);

 private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }
  inline void *MaybeArenaPtr() const {
    return NULL;
  }

 public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // required double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // required double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // required double w = 4;
  bool has_w() const;
  void clear_w();
  static const int kWFieldNumber = 4;
  double w() const;
  void set_w(double value);

  // @@protoc_insertion_point(class_scope:tutorial.Rotation)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_w();
  void clear_has_w();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double x_;
  double y_;
  double z_;
  double w_;
  friend struct ::protobuf_sensor_5fextrinsic_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SensorExtrinsic : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tutorial.SensorExtrinsic) */ {
 public:
  SensorExtrinsic();
  virtual ~SensorExtrinsic();

  SensorExtrinsic(const SensorExtrinsic &from);

  inline SensorExtrinsic &operator=(const SensorExtrinsic &from) {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  SensorExtrinsic(SensorExtrinsic &&from) noexcept
      : SensorExtrinsic() {
    *this = ::std::move(from);
  }

  inline SensorExtrinsic &operator=(SensorExtrinsic &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  inline const ::google::protobuf::UnknownFieldSet &unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet *mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor *descriptor();
  static const SensorExtrinsic &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const SensorExtrinsic *internal_default_instance() {
    return reinterpret_cast<const SensorExtrinsic *>(
        &_SensorExtrinsic_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
      2;

  void Swap(SensorExtrinsic *other);
  friend void swap(SensorExtrinsic &a, SensorExtrinsic &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SensorExtrinsic *New() const final {
    return CreateMaybeMessage<SensorExtrinsic>(NULL);
  }

  SensorExtrinsic *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<SensorExtrinsic>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const SensorExtrinsic &from);
  void MergeFrom(const SensorExtrinsic &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

 private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorExtrinsic *other);

 private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }
  inline void *MaybeArenaPtr() const {
    return NULL;
  }

 public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tutorial.Translation translation = 1;
  int translation_size() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  ::tutorial::Translation *mutable_translation(int index);
  ::google::protobuf::RepeatedPtrField<::tutorial::Translation> *
  mutable_translation();
  const ::tutorial::Translation &translation(int index) const;
  ::tutorial::Translation *add_translation();
  const ::google::protobuf::RepeatedPtrField<::tutorial::Translation> &
  translation() const;

  // repeated .tutorial.Rotation rotation = 2;
  int rotation_size() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  ::tutorial::Rotation *mutable_rotation(int index);
  ::google::protobuf::RepeatedPtrField<::tutorial::Rotation> *
  mutable_rotation();
  const ::tutorial::Rotation &rotation(int index) const;
  ::tutorial::Rotation *add_rotation();
  const ::google::protobuf::RepeatedPtrField<::tutorial::Rotation> &
  rotation() const;

  // @@protoc_insertion_point(class_scope:tutorial.SensorExtrinsic)
 private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField<::tutorial::Translation> translation_;
  ::google::protobuf::RepeatedPtrField<::tutorial::Rotation> rotation_;
  friend struct ::protobuf_sensor_5fextrinsic_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// Translation

// required double x = 1;
inline bool Translation::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Translation::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Translation::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Translation::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Translation::x() const {
  // @@protoc_insertion_point(field_get:tutorial.Translation.x)
  return x_;
}
inline void Translation::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Translation.x)
}

// required double y = 2;
inline bool Translation::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Translation::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Translation::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Translation::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Translation::y() const {
  // @@protoc_insertion_point(field_get:tutorial.Translation.y)
  return y_;
}
inline void Translation::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Translation.y)
}

// required double z = 3;
inline bool Translation::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Translation::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Translation::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Translation::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Translation::z() const {
  // @@protoc_insertion_point(field_get:tutorial.Translation.z)
  return z_;
}
inline void Translation::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Translation.z)
}

// -------------------------------------------------------------------

// Rotation

// required double x = 1;
inline bool Rotation::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Rotation::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Rotation::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Rotation::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Rotation::x() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.x)
  return x_;
}
inline void Rotation::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Rotation.x)
}

// required double y = 2;
inline bool Rotation::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Rotation::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Rotation::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Rotation::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Rotation::y() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.y)
  return y_;
}
inline void Rotation::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Rotation.y)
}

// required double z = 3;
inline bool Rotation::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Rotation::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Rotation::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Rotation::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Rotation::z() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.z)
  return z_;
}
inline void Rotation::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Rotation.z)
}

// required double w = 4;
inline bool Rotation::has_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Rotation::set_has_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Rotation::clear_has_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Rotation::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline double Rotation::w() const {
  // @@protoc_insertion_point(field_get:tutorial.Rotation.w)
  return w_;
}
inline void Rotation::set_w(double value) {
  set_has_w();
  w_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Rotation.w)
}

// -------------------------------------------------------------------

// SensorExtrinsic

// repeated .tutorial.Translation translation = 1;
inline int SensorExtrinsic::translation_size() const {
  return translation_.size();
}
inline void SensorExtrinsic::clear_translation() {
  translation_.Clear();
}
inline ::tutorial::Translation *SensorExtrinsic::mutable_translation(int index) {
  // @@protoc_insertion_point(field_mutable:tutorial.SensorExtrinsic.translation)
  return translation_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::tutorial::Translation> *
SensorExtrinsic::mutable_translation() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.SensorExtrinsic.translation)
  return &translation_;
}
inline const ::tutorial::Translation &SensorExtrinsic::translation(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.SensorExtrinsic.translation)
  return translation_.Get(index);
}
inline ::tutorial::Translation *SensorExtrinsic::add_translation() {
  // @@protoc_insertion_point(field_add:tutorial.SensorExtrinsic.translation)
  return translation_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::tutorial::Translation> &
SensorExtrinsic::translation() const {
  // @@protoc_insertion_point(field_list:tutorial.SensorExtrinsic.translation)
  return translation_;
}

// repeated .tutorial.Rotation rotation = 2;
inline int SensorExtrinsic::rotation_size() const {
  return rotation_.size();
}
inline void SensorExtrinsic::clear_rotation() {
  rotation_.Clear();
}
inline ::tutorial::Rotation *SensorExtrinsic::mutable_rotation(int index) {
  // @@protoc_insertion_point(field_mutable:tutorial.SensorExtrinsic.rotation)
  return rotation_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::tutorial::Rotation> *
SensorExtrinsic::mutable_rotation() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.SensorExtrinsic.rotation)
  return &rotation_;
}
inline const ::tutorial::Rotation &SensorExtrinsic::rotation(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.SensorExtrinsic.rotation)
  return rotation_.Get(index);
}
inline ::tutorial::Rotation *SensorExtrinsic::add_rotation() {
  // @@protoc_insertion_point(field_add:tutorial.SensorExtrinsic.rotation)
  return rotation_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::tutorial::Rotation> &
SensorExtrinsic::rotation() const {
  // @@protoc_insertion_point(field_list:tutorial.SensorExtrinsic.rotation)
  return rotation_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// @@protoc_insertion_point(namespace_scope)

} // namespace tutorial

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_sensor_5fextrinsic_2eproto
